organization: andreasisnes
team: Team Access Management
repositories:
  - access-management
  - access-management-frontend
  - authorization
subscriptions:
  dev: ff5f6913-f6bc-420c-ba78-5bc1e3fe4895
  test: ff5f6913-f6bc-420c-ba78-5bc1e3fe4895
  staging: ff5f6913-f6bc-420c-ba78-5bc1e3fe4895
  prod: ff5f6913-f6bc-420c-ba78-5bc1e3fe4895

members:
  developers:
    - github: andreasisnes
    - github:

  admins:
    - github: jonkjetiloye
