organization: andreasisnes
team: Team Access Management
repositories:
  - access-management
  - access-management-frontend
  - authorization

subscriptions:
  at21: ff5f6913-f6bc-420c-ba78-5bc1e3fe4895
  at22: ff5f6913-f6bc-420c-ba78-5bc1e3fe4895
  at23: ff5f6913-f6bc-420c-ba78-5bc1e3fe4895
  at24: ff5f6913-f6bc-420c-ba78-5bc1e3fe4895
  at25: ff5f6913-f6bc-420c-ba78-5bc1e3fe4895
  tt02: ff5f6913-f6bc-420c-ba78-5bc1e3fe4895
  prod: ff5f6913-f6bc-420c-ba78-5bc1e3fe4895

members:
  developers:
    - github: andreasisnes
    - github:

  admins:
    - github: jonkjetiloye
