name: "Terraform Initialize"
description: "Greet someone"
inputs:
  working_directory:
    description: Terraform project
    default: ./infrastructure
    required: true
  arm_client_id:
    required: true
    description: Azure Client ID
  arm_subscription_id:
    required: true
    description: Azure Subscription ID
  arm_tenant_id:
    description: Azure Tenant ID
    default: 90633377-f76d-4d53-9675-43240c2d6f62
  tf_args:
    description: Args
  tf_version:
    description: Terraform Version
    default: 1.7.4
  tf_log_level:
    description: "Log level"
    default: "INFO"

runs:
  using: "composite"
  steps:
    - name: Azure login
      uses: azure/login@v2
      with:
        client-id: ${{ inputs.arm_client_id }}
        tenant-id: ${{ inputs.arm_tenant_id }}
        subscription-id: ${{ inputs.arm_subscription_id }}

    - name: Terraform Apply
      working-directory: ${{ inputs.working_directory }}
      shell: bash
      env:
        ARM_CLIENT_ID: ${{ inputs.arm_client_id }}
        ARM_SUBSCRIPTION_ID: ${{ inputs.arm_subscription_id }}
        ARM_TENANT_ID: ${{ inputs.arm_tenant_id }}
        ARM_USE_OIDC: "true"
      run: |
        terraform apply -auto-approve ${{ inputs.tf_args }}
