name: "Terraform Initialize"
description: "Greet someone"
inputs:
  working_dir:
    description: Terraform project
    default: ./infrastructure
    required: true
  environment:
    description: Environment <AT21, AT22, AT23, AT24, AT25, TT02, PROD>
  arm_client_id:
    required: true
    description: Azure Client ID
  arm_subscription_id:
    required: true
    description: Azure Subscription ID
    default: ff5f6913-f6bc-420c-ba78-5bc1e3fe4895
  arm_tenant_id:
    description: Azure Tenant ID
    default: 90633377-f76d-4d53-9675-43240c2d6f62
  arm_resource_group_name:
    description: Resource Group Name
    default: rgandreasisnesstorage001
  arm_storage_account_name:
    description: Storage Account Name
    default: standreasisnesstorage001
  tf_version:
    description: Terraform Version
    default: 1.7.4
  tf_log_level:
    description: "Log level"
    default: "INFO"

runs:
  using: "composite"
  steps:
    - name: Terraform Install
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: ${{ inputs.tf_version }}
        terraform_wrapper: false

    - name: Echo
      shell: bash
      run: echo ${{ vars.ARM_STORAGE_ACCOUNT_NAME }}
    - name: Terraform Set Logger
      shell: bash
      run: export TF_LOG="${{ inputs.tf_log_level == '' && 'INFO' || inputs.tf_log_level }}"

    - name: Terraform Init State
      shell: bash
      working-directory: Repositories
      env:
        ARM_CLIENT_ID: ${{ inputs.arm_client_id }}
        ARM_SUBSCRIPTION_ID: ${{ inputs.arm_subscription_id }}
        ARM_TENANT_ID: ${{ inputs.arm_tenant_id }}
        ARM_USE_OIDC: "true"
      run: |
        terraform init \
          -backend-config="resource_group_name=${{ inputs.arm_resource_group_name }}" \
          -backend-config="storage_account_name=${{ inputs.arm_storage_account_name }}" \
          -backend-config="container_name=$(echo "github-${GITHUB_REPOSITORY#*/}-${{ inputs.environment }}" | tr '[:upper:]' '[:lower:]')" \
          -backend-config="key=tfstate"
