name: Repository
on: [push]

env:
  TERRAFORM_VERSION: 1.7.4

jobs:
  deploy:
    environment: dev
    permissions:
      id-token: write
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v1
      - name: Azure CLI script
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: |
            az account show
      - name: Terraform Install
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}
          terraform_wrapper: false
      - name: Terraform Init
        working-directory: Repositories
        env:
          ARM_CLIENT_ID: 3652cacb-6e22-49fd-9c08-bca5c11a285c
          ARM_SUBSCRIPTION_ID: ff5f6913-f6bc-420c-ba78-5bc1e3fe4895
          ARM_TENANT_ID: 90633377-f76d-4d53-9675-43240c2d6f62
          ARM_USE_OIDC: true
        run: |
          terraform init \
          -backend-config="resource_group_name=${{ vars.ARM_RESOURCE_GROUP_NAME }}" \
          -backend-config="storage_account_name=${{ vars.ARM_STORAGE_ACCOUNT_NAME }}" \
          -backend-config="container_name=github-${GITHUB_REPOSITORY#*/}-dev" \
          -backend-config="key=tfstate"
